spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ewm
    username: test
    password: test
  h2:
    console:
      enabled: true

stat-server:
  url: http://localhost:9090