server:
  port: 8080

spring:
  profiles:
    active: local
#    active: docker
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        show_sql: true
#        format_sql: true
#  sql:
#    init:
#      mode: always
logging:
  level:
    ru.practicum.explorewithme: trace
