version: '3.8'
services:

  stats-server:
    build: stats-server
    ports:
      - "9090:9090"
    container_name: stats-server
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    container_name: stats-db
    environment:
      - POSTGRES_DB=stats_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ewm-service
    ports:
      - "8080:8080"
    container_name: main-server
    depends_on:
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=groot

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=groot